name: 'Continuous Delivery'        
        
on:        
  push:        
    branches:        
      - 'main'  # This will make the workflow run on every push to the main branch    
        
jobs:     
  deploy-to-gcp:        
    runs-on: ubuntu-latest     
    steps:     
    - name: Checkout        
      uses: actions/checkout@v2        
        
    - name: Set up Cloud SDK        
      uses: google-github-actions/setup-gcloud@v1.1.1        
      with:        
        service_account_key: ${{ secrets.GCP_SA_KEY }}        
        project_id: mle-challenge        
        
    - name: Deploy to Google Cloud Run        
      run: gcloud run deploy mle-challenge-service --image gcr.io/mle-challenge/mle-challenge:v1 --region southamerica-east1 --project mle-challenge