name: 'Continuous Integration'  
  
on:  
  push:  
    branches:  
      - '*'  # This will make the workflow run on every push  
  
jobs:  
  build-and-test:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Checkout  
      uses: actions/checkout@v2  
  
    - name: Set up Cloud SDK  
      uses: google-github-actions/setup-gcloud@v0.2.1  
      with:  
        service_account_key: ${{ secrets.GCP_SA_KEY }}  
        project_id: mle-challenge  
        
    - name: Configure Docker to use the gcloud command-line tool as a credential helper        
      run: gcloud auth configure-docker   
  
    - name: Build Docker image  
      run: docker build -t gcr.io/mle-challenge/mle-challenge:v1 .  
  
    - name: Run Model Tests  
      run: docker run --rm gcr.io/mle-challenge/mle-challenge:v1 make model-test  
  
    - name: Run API Tests  
      run: docker run --rm gcr.io/mle-challenge/mle-challenge:v1 make api-test  
  
    - name: Push Docker image if tests pass  
      run: docker push gcr.io/mle-challenge/mle-challenge:v1